INSERT INTO unit VALUES ('kilogram', 'kg', 1, 'SOLID');
INSERT INTO unit VALUES ('gram', 'g', 0.001, 'SOLID');
INSERT INTO unit VALUES ('milligram', 'mg', 0.000001, 'SOLID');
INSERT INTO unit VALUES ('liter', 'l', 1, 'LIQUID');
INSERT INTO unit VALUES ('desiliter', 'dl', 0.1, 'LIQUID');
INSERT INTO unit VALUES ('centiliter', 'cl', 0.01, 'LIQUID');
INSERT INTO unit VALUES ('milliliter', 'ml', 0.001, 'LIQUID');
INSERT INTO unit VALUES ('spiseskje', 'ss', 0.0147867648, 'LIQUID');
INSERT INTO unit VALUES ('teskje', 'ts', 0.00492892159, 'LIQUID');
INSERT INTO unit VALUES ('stykk', 'stk', 1, 'BY_PIECE');

INSERT INTO ingredient VALUES (1, 'fast tofu','gram');
INSERT INTO ingredient VALUES (2, 'kikertemel','spiseskje');
INSERT INTO ingredient VALUES (3, 'rapsolje','spiseskje');
INSERT INTO ingredient VALUES (4, 'hjertesalat','stykk');
INSERT INTO ingredient VALUES (5, 'tomater','stykk');
INSERT INTO ingredient VALUES (6, 'paprika','stykk');
INSERT INTO ingredient VALUES (7, 'avokado','stykk');
INSERT INTO ingredient VALUES (8, 'tortillas','stykk');
INSERT INTO ingredient VALUES (9, 'ketjap manis','spiseskje');
INSERT INTO ingredient VALUES (10, 'soyasaus','spiseskje');
INSERT INTO ingredient VALUES (11, 'lønnesirup','spiseskje');
INSERT INTO ingredient VALUES (12, 'sriracha saus','teskje');
INSERT INTO ingredient VALUES (13, 'ferdig kokt sushiris','spiseskje');
INSERT INTO ingredient VALUES (14, 'rå lakseloin','gram');
INSERT INTO ingredient VALUES (15, 'liten avokado','stykk');
INSERT INTO ingredient VALUES (16, 'vårløk','stykk');
INSERT INTO ingredient VALUES (17, 'syltet rødløk','spiseskje');
INSERT INTO ingredient VALUES (18, 'chilimajones','spiseskje');
INSERT INTO ingredient VALUES (19, 'salmaburger','stykk');
INSERT INTO ingredient VALUES (20, 'salt','stykk');
INSERT INTO ingredient VALUES (21, 'pepper','stykk');
INSERT INTO ingredient VALUES (22, 'grove hamburgerbrød','stykk');
INSERT INTO ingredient VALUES (23, 'babyspinat','stykk');
INSERT INTO ingredient VALUES (24, 'aspargesbønner','stykk');
INSERT INTO ingredient VALUES (25, 'løk','stykk');
INSERT INTO ingredient VALUES (26, 'brokkoli','stykk');
INSERT INTO ingredient VALUES (27, 'rød chili','stykk');
INSERT INTO ingredient VALUES (28, 'kokosmelk','stykk');
INSERT INTO ingredient VALUES (29, 'grønn curry paste','teskje');
INSERT INTO ingredient VALUES (30, 'store villreker','gram');
INSERT INTO ingredient VALUES (31, 'fiskesaus','teskje');
INSERT INTO ingredient VALUES (32, 'lime','stykk');
INSERT INTO ingredient VALUES (33, 'frisk koriander','stykk');
INSERT INTO ingredient VALUES (34, 'superris, evt quinoa eller villris','stykk');
INSERT INTO ingredient VALUES (35, 'lakseloin','gram');
INSERT INTO ingredient VALUES (36, 'limesaft','spiseskje');
INSERT INTO ingredient VALUES (37, 'sesamfrø','spiseskje');
INSERT INTO ingredient VALUES (38, 'mango','stykk');
INSERT INTO ingredient VALUES (39, 'granateple','stykk');
INSERT INTO ingredient VALUES (40, 'råkost mix','stykk');
INSERT INTO ingredient VALUES (41, 'sukkererter','stykk');