version: '3.1'

services:
  db:
    image: mysql:8.0.32
    env_file:
      - ../.env
    ports:
      - 3306:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
